# Generated by Django 4.2.5 on 2023-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_options_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='images/picture.png', null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Picture'),
        ),
    ]
