# Generated by Django 4.2.5 on 2023-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
