# Generated by Django 4.2.5 on 2023-09-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Picture'),
        ),
    ]
