# Generated by Django 4.2.5 on 2023-09-30 20:09

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
