# Generated by Django 4.2.5 on 2023-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
